[package]
name = "list-comprehensions"
version = "0.1.0"
authors = ["Elihu Cruz <ecruz@earnest.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
